FROM node:20-slim

RUN apt-get update && apt-get install -y --no-install-recommends openssl poppler-utils && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 3001
CMD ["sh", "-c", "npx prisma generate && npm run dev"]
