ALTER TABLE "Investment"
ADD COLUMN "ticker" TEXT,
ADD COLUMN "isin" TEXT,
ADD COLUMN "exchange" TEXT,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'EUR',
ADD COLUMN "units" DOUBLE PRECISION,
ADD COLUMN "unitPrice" DOUBLE PRECISION;
